input {
    jmx {
        path => "/usr/share/logstash/pipeline/jmx_conf"
        polling_frequency => 2
        type => "jmx"
    }
}

output {
  stdout {
    codec => rubydebug
  }
  elasticsearch {
    hosts => "elasticsearch:9200"
    index => "kafka_mon"
#    user => "logstash_internal"
#    password => "${LOGSTASH_INTERNAL_PASSWORD}"
    user => "elastic"
    password => "changeme" 
    ecs_compatibility => disabled
  }
}
