input {
        kafka {
                bootstrap_servers => "broker-1:19092,broker-2:19092,broker-3:19092"
                group_id => "logstash"
                topics => [ "webapp-logs" ]
                consumer_threads => 1
                codec => json{}
        }
}

## Add your filters / logstash plugins configuration here
filter {
        grok {
                match => {
                        "message" => "%{COMBINEDAPACHELOG}"
                }
                remove_field => "message"
        }
}

output {
	elasticsearch {
		hosts => "elasticsearch:9200"
		user => "logstash_internal"
		password => "${LOGSTASH_INTERNAL_PASSWORD}"
                ecs_compatibility => disabled
	}
}
